# Generated by Django 4.1.3 on 2022-11-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Organization Email')),
            ],
            options={
                'verbose_name': 'Organization name',
                'verbose_name_plural': 'Organization names',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Work Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Work End Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Work End Time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='webapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Work Time',
                'verbose_name_plural': 'Users Work Times',
                'db_table': 'userworktimes',
            },
        ),
        migrations.CreateModel(
            name='OrganizationWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Work Start Time')),
                ('end_time', models.TimeField(verbose_name='Work End Time')),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.organization')),
            ],
            options={
                'verbose_name': 'Organization Work Time',
                'verbose_name_plural': 'Organizations Work Times',
                'db_table': 'organizationworktimes',
            },
        ),
    ]
